### ISSUE TITLE
[Feature] update content in the CV

### ISSUE THREAD

**Issue by Lordmzn** [Lordmzn/cv#2]
# current

I have two EuroPass versions, italian and english, and another one-page one in italian

#  TODO

- [x] explore options to manage versions in the same repo with branches
- [x] deepen the enersem description
- [x] finally, update the english version
